[global]
use-profiles = ["default"]

[repository]
repository = "/home/pcloud/Misc/Backups/kubuntu"
password-command = "op read op://Private/xrgzk4qnqpsecqyxlsxpucssji/password"

[backup]
host = "kubuntu"
glob-files = ["~/.config/rustic/default.glob", "~/.config/rustic/kubuntu.glob"]

[[backup.snapshots]]
sources = ["/"]
