[global]
use-profiles = ["default"]

[repository]
#repository = "/Users/meow/pCloud Drive/Misc/Backups/macintosh"
repository = "/home/pcloud/Misc/Backups/macintosh"
password-command = "op read op://Private/o7hdiy7mwdifj2k7dmvq2qbl6a/password"

[backup]
host = "macintosh"
glob-files = [
  "/home/meow/.config/rustic/default.glob",
  "/home/meow/.config/rustic/macintosh.glob",
]

[[backup.snapshots]]
sources = ["/"]
