[global]
use-profiles = ["default"]

[repository]
repository = "/opt/pcloud/Misc/Backups/macintosh"
password-command = "opunattended op://Private/o7hdiy7mwdifj2k7dmvq2qbl6a/password"

[backup]
host = "macintosh"
glob-files = ["/opt/rustic/default.glob", "/opt/rustic/macintosh.glob"]

[[backup.snapshots]]
sources = ["/"]
