[global]
use-profiles = ["default"]

[repository]
repository = "/opt/pcloud/Misc/Backups/meow-pc"
password-command = "opunattended op://Private/eirlaudkqrmqs3wiv3uxt5lv5i/password"

[backup]
host = "meow-pc"
glob-files = ["/opt/rustic/default.glob", "/opt/rustic/meow-pc.glob"]

[[backup.snapshots]]
sources = ["/"]
